# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jsonmodel}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rodrigo Alvarez"]
  s.date = %q{2012-01-21}
  s.description = %q{This gem allows you to create dynamic classes (models) based on a JSON Schema, providing validations and being compliant with ActiveModel.}
  s.email = %q{papipo@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/config/locales/en.yml",
    "lib/jsonmodel.rb",
    "lib/jsonmodel/attributes.rb",
    "lib/jsonmodel/persistence.rb",
    "lib/jsonmodel/types.rb",
    "lib/jsonmodel/validations.rb",
    "test/helper.rb",
    "test/schemas/product.json",
    "test/test_activemodel_lint.rb",
    "test/test_jsonmodel.rb"
  ]
  s.homepage = %q{http://github.com/Papipo/jsonmodel}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Dynamic Active Model compliant models via JSON Schema}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<activemodel>, ["= 3.1.0.rc4"])
      s.add_development_dependency(%q<activesupport>, ["= 3.1.0.rc4"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<activemodel>, ["= 3.1.0.rc4"])
      s.add_dependency(%q<activesupport>, ["= 3.1.0.rc4"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<activemodel>, ["= 3.1.0.rc4"])
    s.add_dependency(%q<activesupport>, ["= 3.1.0.rc4"])
  end
end

