# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "jsonmodel"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rodrigo Alvarez"]
  s.date = "2012-01-23"
  s.description = "This gem allows you to create dynamic classes (models) based on a JSON Schema, providing validations and being compliant with ActiveModel."
  s.email = "papipo@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "jsonmodel.gemspec",
    "lib/config/locales/en.yml",
    "lib/jsonmodel.rb",
    "lib/jsonmodel/attributes.rb",
    "lib/jsonmodel/naming.rb",
    "lib/jsonmodel/persistence.rb",
    "lib/jsonmodel/types.rb",
    "lib/jsonmodel/validations.rb",
    "lib/jsonmodel/validations/array_validator.rb",
    "test/helper.rb",
    "test/test_activemodel_lint.rb",
    "test/test_jsonmodel.rb"
  ]
  s.homepage = "http://github.com/Papipo/jsonmodel"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Dynamic Active Model compliant models via JSON Schema"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activemodel>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rails>, ["~> 3.2.0.rc"])
    else
      s.add_dependency(%q<activemodel>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rails>, ["~> 3.2.0.rc"])
    end
  else
    s.add_dependency(%q<activemodel>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rails>, ["~> 3.2.0.rc"])
  end
end

